name: Run NUnit Tests and Build Docker Image

on:
  push:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore --configuration Release

      - name: Test with NUnit
        run: dotnet test --no-build --configuration Release --logger:"console;verbosity=normal"

      # --- Build Docker image ---
      - name: Build Docker image
        run: docker build -t calculatorapp:latest .

      # --- Optional: Log in to Docker Hub ---
      - name: Log in to Docker Hub
        if: github.ref == 'refs/heads/master'  # Only on pushes to master
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.2170199 }}
          password: ${{ secrets.Sumanta@123 }}

      # --- Optional: Push Docker image ---
      - name: Push Docker image to Docker Hub
        if: github.ref == 'refs/heads/master'  # Only on pushes to master
        run: |
          docker tag calculatorapp:latest ${{ secrets.DOCKER_USERNAME }}/calculatorapp:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/calculatorapp:latest
